name: harish project workflow
on: push

env:
  REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -name: deploy container to git hub package registry
      shell: bash
      run: ./.github/scripts/test_git_actions.sh
